
# yaml语法  vs .properties只能保存键值对
# 对空格的要求严格

#键值对
server:
  port: 8081

#对象
student:
  name: clare
  age: 24

#对象的行内写法
student2: {name: clare,age:24}

#数组
pets:
  - cat
  - dog
  - elephant

pets2: [cat,dog,pig]


person:
  name: ${random.uuid}
  age: 19
  happy: true
  birth: 2000/05/13
  maps: {k1: v1,k2: v2}
  hello: happy
  lists: [cat,love,bow]
  dog:
    # :hello是占位符
    name: ${person.hello:hello}旺财
    age: 3

#springboot的多环境配置：可以选择激活哪一个配置文件
spring:
  profiles:
    active: dev
debug: true
